export const endpoints  = {
  home: '/',
  categories: '/categories',
  loginOtpRequest: '/auth/otp/request',
  authOtp: '/auth/login/otp',
  authPassword: '/auth/login/password',
  authUser: '/auth/user',
  logout: '/auth/logout',
  product: (id) => `/products/${id}`,
  ProductReview: (id) => `/products/${id}/reviews`,
  accountDashboard: '/account/dashboard',
  accountInformation: '/account/information',
  accountAvatar: '/account/avatar',
  orders: '/account/orders',
  notifications: '/account/notifications',
  notification: (id) => `/account/notifications/${id}`,
  notifMarkAsRead: (id) => `/account/notifications/${id}/read`,
  notifMarkAsReadAll: '/account/notifications/read',
  addresses: '/account/addresses',
  address: (id) => `/account/addresses/${id}`,
  setDefaultAddr: (id) => `/account/addresses/${id}/default`,
  cart: '/cart',
  cartAction: (id) => `/cart/${id}`,
  cartClear: '/cart/clear',
  cartMerge: '/cart/merge',
  wishlist: '/wishlist',
  wishlistItem: (id) => `/wishlist/item/${id}`,
}
