<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [

            // ==================== 1. SMARTPHONES (Category ID: 1) ====================
            [
                'brand_id' => 1,
                'category_id' => 1,
                'name' => 'iPhone 15 Pro Max',
                'price' => 1199.00,
                'discount' => 10,
                'sku' => 'APL-IP15PM-256',
                'description' => 'Apple iPhone 15 Pro Max with A17 Pro chip, titanium body, 48MP main camera, and USB-C. Features a stunning 6.7-inch Super Retina XDR display with ProMotion technology.',
                'short_description' => 'Apple flagship with A17 Pro chip and titanium design.',
                'stock' => 35,
                'image' => 'products/iPhone-15-Pro-Max.webp',
                'sold_count' => 1250,
                'view_count' => 45200,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.221,
                'meta' => ['chip' => 'A17 Pro', 'display' => '6.7-inch Super Retina XDR', 'camera' => '48MP Main'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 1,
                'name' => 'Samsung Galaxy S24 Ultra',
                'price' => 1299.00,
                'discount' => 8,
                'sku' => 'SAM-S24U-512',
                'description' => 'Samsung Galaxy S24 Ultra with titanium frame, Galaxy AI, 200MP camera, S Pen support, and Snapdragon 8 Gen 3 processor for unmatched productivity and creativity.',
                'short_description' => 'Ultimate Android flagship with Galaxy AI and S Pen.',
                'stock' => 50,
                'image' => 'products/samsung-galaxy-s24-ultra-5g-sm.webp',
                'sold_count' => 980,
                'view_count' => 38700,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.232,
                'meta' => ['chip' => 'Snapdragon 8 Gen 3', 'camera' => '200MP', 'feature' => 'Galaxy AI, S Pen Support'],
            ],
            [
                'brand_id' => 13,
                'category_id' => 1,
                'name' => 'Xiaomi 14 Pro',
                'price' => 899.00,
                'discount' => 12,
                'sku' => 'XIA-M14P-256',
                'description' => 'Xiaomi 14 Pro featuring Leica Summilux optical lens, Snapdragon 8 Gen 3, 120W HyperCharge, and a brilliant 6.73-inch LTPO AMOLED display with variable refresh rate.',
                'short_description' => 'Leica-powered flagship with 120W super-fast charging.',
                'stock' => 45,
                'image' => 'products/xiaomi-14-pro-5g-dual-sim-512gb-black-16gb-ram-china-version.jpg',
                'sold_count' => 670,
                'view_count' => 21800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.223,
                'meta' => ['chip' => 'Snapdragon 8 Gen 3', 'camera' => 'Leica Summilux Optical Lens', 'charging' => '120W HyperCharge'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 1,
                'name' => 'Samsung Galaxy Z Flip 5',
                'price' => 999.00,
                'discount' => 15,
                'sku' => 'SAM-ZF5-256',
                'description' => 'Samsung Galaxy Z Flip 5 with a larger 3.4-inch cover display, Flex Hinge, Snapdragon 8 Gen 2, and compact foldable design for style and portability.',
                'short_description' => 'Stylish foldable phone with expanded cover screen.',
                'stock' => 30,
                'image' => 'products/samsung-galaxy-z-flip-5.webp',
                'sold_count' => 560,
                'view_count' => 29400,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.187,
                'meta' => ['chip' => 'Snapdragon 8 Gen 2', 'display' => '3.4-inch Cover Display', 'feature' => 'Flex Hinge, Foldable Design'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 1,
                'name' => 'iPhone 15',
                'price' => 799.00,
                'discount' => 5,
                'sku' => 'APL-IP15-128',
                'description' => 'Apple iPhone 15 with Dynamic Island, 48MP main camera, A16 Bionic chip, and USB-C connectivity. Delivers powerful performance in a colorful and durable design.',
                'short_description' => 'Colorful iPhone with Dynamic Island and A16 chip.',
                'stock' => 80,
                'image' => 'products/iphone-15-128.webp',
                'sold_count' => 2100,
                'view_count' => 61200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.171,
                'meta' => ['chip' => 'A16 Bionic', 'camera' => '48MP Main', 'feature' => 'Dynamic Island, USB-C'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 1,
                'name' => 'Samsung Galaxy A55',
                'price' => 449.00,
                'discount' => 10,
                'sku' => 'SAM-GA55-128',
                'description' => 'Samsung Galaxy A55 with 50MP OIS camera, 6.6-inch Super AMOLED display, 5000mAh battery, and IP67 water resistance, offering premium features at an accessible price.',
                'short_description' => 'Mid-range champion with OIS camera and IP67 rating.',
                'stock' => 120,
                'image' => 'products/samsung-galaxy-a55.webp',
                'sold_count' => 3400,
                'view_count' => 78500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.213,
                'meta' => ['camera' => '50MP OIS', 'battery' => '5000mAh', 'rating' => 'IP67 Water Resistance'],
            ],
            [
                'brand_id' => 13,
                'category_id' => 1,
                'name' => 'Xiaomi Redmi Note 13 Pro+',
                'price' => 449.00,
                'discount' => 18,
                'sku' => 'XIA-RN13PP-256',
                'description' => 'Redmi Note 13 Pro+ with 200MP OIS camera, 120W HyperCharge, 1.5K AMOLED display, and MediaTek Dimensity 7200-Ultra for exceptional mid-range photography and speed.',
                'short_description' => '200MP camera and 120W charging at a mid-range price.',
                'stock' => 95,
                'image' => 'products/xiaomi-note-13-pro-plus.webp',
                'sold_count' => 2800,
                'view_count' => 69300,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.204,
                'meta' => ['chip' => 'MediaTek Dimensity 7200-Ultra', 'camera' => '200MP OIS', 'charging' => '120W HyperCharge'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 1,
                'name' => 'Sony Xperia 1 V',
                'price' => 1399.00,
                'discount' => 7,
                'sku' => 'SON-XP1V-256',
                'description' => 'Sony Xperia 1 V with 4K HDR OLED 120Hz display, Exmor T for mobile sensor, real-time Eye AF, and pro-grade video recording capabilities for content creators.',
                'short_description' => 'Professional 4K smartphone for creators.',
                'stock' => 18,
                'image' => 'products/sony-xperia-1-v.webp',
                'sold_count' => 210,
                'view_count' => 11500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.187,
                'meta' => ['display' => '4K HDR OLED 120Hz', 'camera' => 'Exmor T Sensor', 'feature' => 'Real-time Eye AF'],
            ],
            [
                'brand_id' => 13,
                'category_id' => 1,
                'name' => 'Xiaomi Poco F5 Pro',
                'price' => 499.00,
                'discount' => 20,
                'sku' => 'XIA-PF5P-256',
                'description' => 'Poco F5 Pro with Snapdragon 8+ Gen 1, WQHD+ 120Hz AMOLED display, 67W turbo charging, and 5160mAh battery for incredible gaming performance on a budget.',
                'short_description' => 'Flagship gaming performance at a mid-range price.',
                'stock' => 70,
                'image' => 'products/xiaomi-poco-f5-pro.webp',
                'sold_count' => 1350,
                'view_count' => 34200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.204,
                'meta' => ['chip' => 'Snapdragon 8+ Gen 1', 'display' => 'WQHD+ 120Hz AMOLED', 'battery' => '5160mAh'],
            ],
            [
                'brand_id' => 17,
                'category_id' => 1,
                'name' => 'LG Wing 5G',
                'price' => 699.00,
                'discount' => 25,
                'sku' => 'LG-WING-128',
                'description' => 'LG Wing 5G with unique rotating Swivel Mode, 6.8-inch main display, 3.9-inch second screen, Gimbal Motion Camera, and Snapdragon 765G for innovative multitasking.',
                'short_description' => 'Rotating dual-screen smartphone for multitaskers.',
                'stock' => 15,
                'image' => 'products/lg-wing-128.webp',
                'sold_count' => 180,
                'view_count' => 8700,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.260,
                'meta' => ['chip' => 'Snapdragon 765G', 'display' => '6.8-inch Main, 3.9-inch Second Screen', 'feature' => 'Swivel Mode, Gimbal Motion Camera'],
            ],

            // ==================== 2. LAPTOPS (Category ID: 2) ====================
            [
                'brand_id' => 1,
                'category_id' => 2,
                'name' => 'MacBook Pro 16" M3 Max',
                'price' => 3499.00,
                'discount' => 5,
                'sku' => 'APL-MBP16-M3M',
                'description' => 'Apple MacBook Pro 16-inch with M3 Max chip, 32GB unified memory, 1TB SSD, Liquid Retina XDR display, and up to 22 hours battery for uncompromising pro workflow.',
                'short_description' => 'Ultimate pro laptop with M3 Max and stunning XDR display.',
                'stock' => 12,
                'image' => 'products/macbook-pro-16.webp',
                'sold_count' => 280,
                'view_count' => 15200,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 2.15,
                'meta' => ['chip' => 'M3 Max', 'ram' => '32GB Unified', 'storage' => '1TB SSD', 'display' => 'Liquid Retina XDR'],
            ],
            [
                'brand_id' => 7,
                'category_id' => 2,
                'name' => 'Dell XPS 15',
                'price' => 1899.00,
                'discount' => 12,
                'sku' => 'DEL-XPS15-32',
                'description' => 'Dell XPS 15 with 13th Gen Intel Core i7, 32GB RAM, 1TB SSD, NVIDIA RTX 4060, and a stunning 15.6-inch 3.5K OLED display for creative professionals.',
                'short_description' => 'Premium creator laptop with OLED display and RTX graphics.',
                'stock' => 20,
                'image' => 'products/dell-xps-15.webp',
                'sold_count' => 340,
                'view_count' => 14300,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 1.86,
                'meta' => ['cpu' => '13th Gen Intel Core i7', 'gpu' => 'NVIDIA RTX 4060', 'ram' => '32GB', 'storage' => '1TB SSD', 'display' => '15.6-inch 3.5K OLED'],
            ],
            [
                'brand_id' => 9,
                'category_id' => 2,
                'name' => 'Lenovo ThinkPad X1 Carbon Gen 11',
                'price' => 1799.00,
                'discount' => 15,
                'sku' => 'LEN-X1C11-16',
                'description' => 'Lenovo ThinkPad X1 Carbon Gen 11 with Intel Core i7-1355U, 16GB RAM, 512GB SSD, 14-inch 2.8K OLED, and MIL-STD-810H durability in an ultralight 1.12kg chassis.',
                'short_description' => 'Ultralight business laptop with military-grade durability.',
                'stock' => 25,
                'image' => 'products/lenovo-thinkpad-x1.webp',
                'sold_count' => 410,
                'view_count' => 16800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.12,
                'meta' => ['cpu' => 'Intel Core i7-1355U', 'ram' => '16GB', 'storage' => '512GB SSD', 'display' => '14-inch 2.8K OLED', 'feature' => 'MIL-STD-810H Durability'],
            ],
            [
                'brand_id' => 8,
                'category_id' => 2,
                'name' => 'HP Spectre x360 14',
                'price' => 1649.00,
                'discount' => 10,
                'sku' => 'HP-SPX360-16',
                'description' => 'HP Spectre x360 14 convertible with Intel Core Ultra 7, 16GB RAM, 1TB SSD, 14-inch 2.8K OLED touchscreen, and included rechargeable MPP 2.0 pen for versatile productivity.',
                'short_description' => 'Premium 2-in-1 with OLED and included pen.',
                'stock' => 22,
                'image' => 'products/hp-spectre-x360-14.webp',
                'sold_count' => 290,
                'view_count' => 12700,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.37,
                'meta' => ['cpu' => 'Intel Core Ultra 7', 'ram' => '16GB', 'storage' => '1TB SSD', 'display' => '14-inch 2.8K OLED Touchscreen', 'feature' => '2-in-1 Convertible'],
            ],
            [
                'brand_id' => 10,
                'category_id' => 2,
                'name' => 'ASUS ROG Zephyrus G14',
                'price' => 1599.00,
                'discount' => 10,
                'sku' => 'ASU-ZG14-4060',
                'description' => 'ASUS ROG Zephyrus G14 gaming laptop with AMD Ryzen 9 7940HS, 16GB RAM, RTX 4060, 1TB SSD, 14-inch QHD 165Hz display, and AniMe Matrix LED array on the lid.',
                'short_description' => 'Compact gaming powerhouse with AniMe Matrix LEDs.',
                'stock' => 18,
                'image' => 'products/asus-rog-g14.webp',
                'sold_count' => 380,
                'view_count' => 22300,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 1.72,
                'meta' => ['cpu' => 'AMD Ryzen 9 7940HS', 'gpu' => 'NVIDIA RTX 4060', 'ram' => '16GB', 'storage' => '1TB SSD', 'display' => '14-inch QHD 165Hz', 'feature' => 'AniMe Matrix LED'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 2,
                'name' => 'MacBook Air 15" M2',
                'price' => 1299.00,
                'discount' => 8,
                'sku' => 'APL-MBA15-M2',
                'description' => 'Apple MacBook Air 15-inch with M2 chip, 8GB unified memory, 256GB SSD, Liquid Retina display, 1080p FaceTime HD camera, and up to 18 hours battery in a thin fanless design.',
                'short_description' => 'Thin 15-inch laptop with M2 chip and all-day battery.',
                'stock' => 40,
                'image' => 'products/macbook-air-15.webp',
                'sold_count' => 820,
                'view_count' => 34500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.51,
                'meta' => ['chip' => 'M2', 'ram' => '8GB Unified', 'storage' => '256GB SSD', 'display' => 'Liquid Retina', 'feature' => 'Fanless Design'],
            ],
            [
                'brand_id' => 20,
                'category_id' => 2,
                'name' => 'Acer Swift Go 14',
                'price' => 799.00,
                'discount' => 12,
                'sku' => 'ACE-SG14-16',
                'description' => 'Acer Swift Go 14 with Intel Core Ultra 7, 16GB RAM, 512GB SSD, 14-inch 2.8K OLED 90Hz display, and AI-powered features in a lightweight aluminum chassis for modern professionals.',
                'short_description' => 'AI-ready ultraportable with brilliant OLED display.',
                'stock' => 35,
                'image' => 'products/acer-go-14.webp',
                'sold_count' => 480,
                'view_count' => 18900,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.25,
                'meta' => ['cpu' => 'Intel Core Ultra 7', 'ram' => '16GB', 'storage' => '512GB SSD', 'display' => '14-inch 2.8K OLED 90Hz', 'feature' => 'AI-Powered'],
            ],
            [
                'brand_id' => 6,
                'category_id' => 2,
                'name' => 'Microsoft Surface Laptop 5',
                'price' => 1299.00,
                'discount' => 10,
                'sku' => 'MIC-SL5-16',
                'description' => 'Microsoft Surface Laptop 5 with Intel Core i7 Evo, 16GB RAM, 512GB SSD, 13.5-inch PixelSense touchscreen, Alcantara palm rest, and Thunderbolt 4 for elegant productivity.',
                'short_description' => 'Elegant touchscreen laptop with luxurious Alcantara finish.',
                'stock' => 28,
                'image' => 'products/microsoft-laptop-5.webp',
                'sold_count' => 520,
                'view_count' => 21400,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.27,
                'meta' => ['cpu' => 'Intel Core i7 Evo', 'ram' => '16GB', 'storage' => '512GB SSD', 'display' => '13.5-inch PixelSense Touchscreen', 'feature' => 'Alcantara Palm Rest'],
            ],
            [
                'brand_id' => 7,
                'category_id' => 2,
                'name' => 'Dell Inspiron 16 Plus',
                'price' => 1099.00,
                'discount' => 15,
                'sku' => 'DEL-I16P-32',
                'description' => 'Dell Inspiron 16 Plus with Intel Core i7-13700H, 32GB RAM, 1TB SSD, NVIDIA RTX 4060, 16-inch 2.5K 120Hz display, and Dolby Atmos speakers for content creation and entertainment.',
                'short_description' => 'Creator-focused laptop with powerful specs and large display.',
                'stock' => 24,
                'image' => 'products/dell-inspiron-16.jpg',
                'sold_count' => 350,
                'view_count' => 14100,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 2.05,
                'meta' => ['cpu' => 'Intel Core i7-13700H', 'gpu' => 'NVIDIA RTX 4060', 'ram' => '32GB', 'storage' => '1TB SSD', 'display' => '16-inch 2.5K 120Hz'],
            ],
            [
                'brand_id' => 9,
                'category_id' => 2,
                'name' => 'Lenovo Yoga 9i',
                'price' => 1399.00,
                'discount' => 12,
                'sku' => 'LEN-Y9I-16',
                'description' => 'Lenovo Yoga 9i convertible with Intel Core i7-1360P, 16GB RAM, 512GB SSD, 14-inch 4K OLED touchscreen, rotating Bowers & Wilkins soundbar, and active pen for versatile creativity.',
                'short_description' => 'Convertible with rotating soundbar and stunning 4K OLED.',
                'stock' => 19,
                'image' => 'products/lenovo-yoga-9i.webp',
                'sold_count' => 260,
                'view_count' => 13100,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.40,
                'meta' => ['cpu' => 'Intel Core i7-1360P', 'ram' => '16GB', 'storage' => '512GB SSD', 'display' => '14-inch 4K OLED Touchscreen', 'feature' => 'Rotating Bowers & Wilkins Soundbar'],
            ],

            // ==================== 3. TABLETS (Category ID: 3) ====================
            [
                'brand_id' => 1,
                'category_id' => 3,
                'name' => 'iPad Pro 12.9" M2',
                'price' => 1099.00,
                'discount' => 8,
                'sku' => 'APL-IPDPRO-M2',
                'description' => 'Apple iPad Pro 12.9-inch with M2 chip, Liquid Retina XDR display with ProMotion, Apple Pencil hover, 5G connectivity, and all-day battery life for creative professionals.',
                'short_description' => 'Ultimate tablet with M2 chip and stunning XDR display.',
                'stock' => 30,
                'image' => 'products/iPad-pro-12.9.webp',
                'sold_count' => 720,
                'view_count' => 31200,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.682,
                'meta' => ['chip' => 'M2', 'display' => 'Liquid Retina XDR', 'feature' => 'ProMotion, Apple Pencil Hover, 5G'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 3,
                'name' => 'Samsung Galaxy Tab S9 Ultra',
                'price' => 1199.00,
                'discount' => 10,
                'sku' => 'SAM-TABS9U',
                'description' => 'Samsung Galaxy Tab S9 Ultra with 14.6-inch Dynamic AMOLED 2X display, Snapdragon 8 Gen 2, IP68 rating, included S Pen, and DeX mode for a full PC-like experience.',
                'short_description' => 'Massive 14.6-inch tablet with IP68 and PC-like DeX mode.',
                'stock' => 22,
                'image' => 'products/samsung-galaxy-tab-s9.webp',
                'sold_count' => 380,
                'view_count' => 18400,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.732,
                'meta' => ['chip' => 'Snapdragon 8 Gen 2', 'display' => '14.6-inch Dynamic AMOLED 2X', 'feature' => 'IP68, S Pen, DeX Mode'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 3,
                'name' => 'iPad Air 11" M2',
                'price' => 599.00,
                'discount' => 5,
                'sku' => 'APL-IPDAIR-M2',
                'description' => 'Apple iPad Air 11-inch with M2 chip, Liquid Retina display, landscape front camera, Apple Pencil Pro support, and vibrant color options for portable productivity and creativity.',
                'short_description' => 'Powerful and colorful tablet with M2 chip.',
                'stock' => 50,
                'image' => 'products/iPad-air-11-451.webp',
                'sold_count' => 1100,
                'view_count' => 38500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.462,
                'meta' => ['chip' => 'M2', 'display' => 'Liquid Retina', 'feature' => 'Apple Pencil Pro Support, Landscape Front Camera'],
            ],
            [
                'brand_id' => 6,
                'category_id' => 3,
                'name' => 'Microsoft Surface Pro 9',
                'price' => 1099.00,
                'discount' => 12,
                'sku' => 'MIC-SP9-16',
                'description' => 'Microsoft Surface Pro 9 with Intel Core i7 Evo, 16GB RAM, 256GB SSD, 13-inch PixelSense Flow touchscreen, Thunderbolt 4, and optional 5G for the most versatile 2-in-1 tablet experience.',
                'short_description' => 'Versatile 2-in-1 tablet that replaces your laptop.',
                'stock' => 25,
                'image' => 'products/microsoft-surface-pro-9.webp',
                'sold_count' => 480,
                'view_count' => 20500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.879,
                'meta' => ['cpu' => 'Intel Core i7 Evo', 'ram' => '16GB', 'storage' => '256GB SSD', 'display' => '13-inch PixelSense Flow Touchscreen', 'feature' => 'Thunderbolt 4, Optional 5G'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 3,
                'name' => 'Samsung Galaxy Tab A9+',
                'price' => 269.00,
                'discount' => 15,
                'sku' => 'SAM-TABA9P',
                'description' => 'Samsung Galaxy Tab A9+ with 11-inch 90Hz display, Snapdragon 695, quad speakers, multi-window support, and Samsung Kids mode for family-friendly entertainment and productivity.',
                'short_description' => 'Affordable family tablet with 90Hz display.',
                'stock' => 80,
                'image' => 'products/samsung-galaxy-tab-s9-plus.webp',
                'sold_count' => 1900,
                'view_count' => 45600,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.480,
                'meta' => ['chip' => 'Snapdragon 695', 'display' => '11-inch 90Hz', 'feature' => 'Quad Speakers, Samsung Kids Mode'],
            ],
            [
                'brand_id' => 9,
                'category_id' => 3,
                'name' => 'Lenovo Tab P12 Pro',
                'price' => 449.00,
                'discount' => 18,
                'sku' => 'LEN-TABP12P',
                'description' => 'Lenovo Tab P12 Pro with 12.6-inch 120Hz AMOLED display, Snapdragon 870, quad JBL speakers, Lenovo Precision Pen 3 included, and productivity mode for work and play.',
                'short_description' => 'Premium Android tablet with AMOLED and included pen.',
                'stock' => 28,
                'image' => 'products/lenovo-tab-p12-pro.webp',
                'sold_count' => 310,
                'view_count' => 12700,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.565,
                'meta' => ['chip' => 'Snapdragon 870', 'display' => '12.6-inch 120Hz AMOLED', 'feature' => 'Quad JBL Speakers, Lenovo Precision Pen 3'],
            ],
            [
                'brand_id' => 13,
                'category_id' => 3,
                'name' => 'Xiaomi Pad 6',
                'price' => 349.00,
                'discount' => 10,
                'sku' => 'XIA-PAD6-128',
                'description' => 'Xiaomi Pad 6 with Snapdragon 870, 11-inch 144Hz 2.8K display, quad Dolby Atmos speakers, and large 8840mAh battery for an immersive entertainment and gaming tablet experience.',
                'short_description' => 'High-refresh rate tablet for entertainment and gaming.',
                'stock' => 45,
                'image' => 'products/xiaomi-pad-6.webp',
                'sold_count' => 620,
                'view_count' => 20300,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.490,
                'meta' => ['chip' => 'Snapdragon 870', 'display' => '11-inch 144Hz 2.8K', 'feature' => 'Quad Dolby Atmos Speakers, 8840mAh Battery'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 3,
                'name' => 'iPad 10th Gen',
                'price' => 449.00,
                'discount' => 8,
                'sku' => 'APL-IPAD10-64',
                'description' => 'Apple iPad 10th generation with A14 Bionic chip, 10.9-inch Liquid Retina display, USB-C, landscape front camera, and Magic Keyboard Folio support in a colorful all-screen design.',
                'short_description' => 'Colorful and capable entry-level iPad with USB-C.',
                'stock' => 65,
                'image' => 'products/iPad-10-plus.webp',
                'sold_count' => 2400,
                'view_count' => 58900,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.477,
                'meta' => ['chip' => 'A14 Bionic', 'display' => '10.9-inch Liquid Retina', 'feature' => 'USB-C, Magic Keyboard Folio Support'],
            ],

            // ==================== 4. HEADPHONES (Category ID: 4) ====================
            [
                'brand_id' => 3,
                'category_id' => 4,
                'name' => 'Sony WH-1000XM5',
                'price' => 399.00,
                'discount' => 20,
                'sku' => 'SON-WH1000XM5',
                'description' => 'Sony WH-1000XM5 wireless headphones with industry-leading noise cancellation, Auto NC Optimizer, 30-hour battery life, crystal-clear hands-free calling, and lightweight comfortable design.',
                'short_description' => 'Industry-leading ANC headphones with 30-hour battery.',
                'stock' => 85,
                'image' => 'products/sony-white-sm-5.webp',
                'sold_count' => 3200,
                'view_count' => 78500,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.250,
                'meta' => ['type' => 'Over-Ear', 'connectivity' => 'Wireless', 'battery' => '30 Hours', 'feature' => 'Active Noise Cancellation'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 4,
                'name' => 'AirPods Pro (2nd Gen)',
                'price' => 249.00,
                'discount' => 12,
                'sku' => 'APL-APP2GEN',
                'description' => 'Apple AirPods Pro 2nd generation with 2x Active Noise Cancellation, Adaptive Transparency, Personalized Spatial Audio, USB-C MagSafe Charging Case, and up to 6 hours listening time.',
                'short_description' => 'Premium earbuds with 2x noise cancellation and spatial audio.',
                'stock' => 120,
                'image' => 'products/air-pods-pro-2nd.webp',
                'sold_count' => 5400,
                'view_count' => 112000,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.054,
                'meta' => ['type' => 'In-Ear', 'chip' => 'Apple H2', 'feature' => '2x Active Noise Cancellation, Adaptive Transparency, Personalized Spatial Audio'],
            ],
            [
                'brand_id' => 15,
                'category_id' => 4,
                'name' => 'Bose QuietComfort Ultra',
                'price' => 429.00,
                'discount' => 15,
                'sku' => 'BOS-QCULTRA-BLK',
                'description' => 'Bose QuietComfort Ultra headphones with Immersive Audio, CustomTune technology, world-class noise cancellation, up to 24 hours battery, and premium materials for luxurious comfort.',
                'short_description' => 'Immersive audio headphones with world-class ANC.',
                'stock' => 45,
                'image' => 'products/bos-quiet-comfort-ultra.webp',
                'sold_count' => 890,
                'view_count' => 31200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.254,
                'meta' => ['type' => 'Over-Ear', 'battery' => '24 Hours', 'feature' => 'Immersive Audio, CustomTune Technology'],
            ],
            [
                'brand_id' => 14,
                'category_id' => 4,
                'name' => 'JBL Tour One M2',
                'price' => 299.00,
                'discount' => 20,
                'sku' => 'JBL-TOM2-BLK',
                'description' => 'JBL Tour One M2 wireless headphones with True Adaptive Noise Cancelling, JBL Pro Audio, spatial 360 sound with head tracking, 50-hour battery, and comfortable over-ear design.',
                'short_description' => 'Adaptive ANC headphones with 50-hour battery life.',
                'stock' => 55,
                'image' => 'products/jbl-tour-one-m2.webp',
                'sold_count' => 730,
                'view_count' => 23400,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.278,
                'meta' => ['type' => 'Over-Ear', 'battery' => '50 Hours', 'feature' => 'True Adaptive ANC, JBL Pro Audio, Spatial 360 Sound'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 4,
                'name' => 'Sony WF-1000XM5',
                'price' => 299.00,
                'discount' => 10,
                'sku' => 'SON-WF1000XM5',
                'description' => 'Sony WF-1000XM5 truly wireless earbuds, the world\'s smallest noise cancelling earbuds, with Hi-Res Audio, Dynamic Driver X, 8-hour battery, and IPX4 water resistance.',
                'short_description' => 'World\'s smallest ANC earbuds with Hi-Res Audio.',
                'stock' => 70,
                'image' => 'products/sony-wf-1000XM5.webp',
                'sold_count' => 1450,
                'view_count' => 42300,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.048,
                'meta' => ['type' => 'In-Ear', 'battery' => '8 Hours', 'feature' => 'Hi-Res Audio, Dynamic Driver X, IPX4'],
            ],
            [
                'brand_id' => 14,
                'category_id' => 4,
                'name' => 'JBL Tune 770NC',
                'price' => 129.00,
                'discount' => 25,
                'sku' => 'JBL-T770NC-BLK',
                'description' => 'JBL Tune 770NC wireless headphones with Adaptive Noise Cancelling, JBL Pure Bass Sound, 44-hour battery life, fast charging, and lightweight foldable design for everyday use.',
                'short_description' => 'Affordable ANC headphones with 44-hour battery.',
                'stock' => 100,
                'image' => 'products/jbl-tune-770NC.webp',
                'sold_count' => 2600,
                'view_count' => 56700,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.232,
                'meta' => ['type' => 'Over-Ear', 'battery' => '44 Hours', 'feature' => 'Adaptive Noise Cancelling, JBL Pure Bass Sound'],
            ],
            [
                'brand_id' => 15,
                'category_id' => 4,
                'name' => 'Bose QuietComfort Earbuds II',
                'price' => 279.00,
                'discount' => 15,
                'sku' => 'BOS-QCEII-BLK',
                'description' => 'Bose QuietComfort Earbuds II with CustomTune sound calibration, world-leading noise cancellation, Aware Mode, IPX4 rating, and three listening modes for personalized audio perfection.',
                'short_description' => 'World-leading noise cancelling earbuds with CustomTune.',
                'stock' => 50,
                'image' => 'products/bos-quiet-comfort-ultra2.webp',
                'sold_count' => 680,
                'view_count' => 25800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.063,
                'meta' => ['type' => 'In-Ear', 'feature' => 'CustomTune Sound Calibration, World-Leading ANC, Aware Mode, IPX4'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 4,
                'name' => 'AirPods Max',
                'price' => 549.00,
                'discount' => 10,
                'sku' => 'APL-APMAX-SLV',
                'description' => 'Apple AirPods Max over-ear headphones with Active Noise Cancellation, Transparency mode, spatial audio with dynamic head tracking, and a stunning design with breathable knit mesh canopy.',
                'short_description' => 'Luxurious over-ear headphones with spatial audio.',
                'stock' => 20,
                'image' => 'products/air-pods-max.webp',
                'sold_count' => 420,
                'view_count' => 18900,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.385,
                'meta' => ['type' => 'Over-Ear', 'chip' => 'Apple H1', 'feature' => 'Active Noise Cancellation, Transparency Mode, Spatial Audio'],
            ],

            // ==================== 5. SMART WATCHES (Category ID: 5) ====================
            [
                'brand_id' => 1,
                'category_id' => 5,
                'name' => 'Apple Watch Series 9',
                'price' => 399.00,
                'discount' => 10,
                'sku' => 'APL-AWS9-45',
                'description' => 'Apple Watch Series 9 with S9 chip, brighter always-on display, double tap gesture, advanced health monitoring including ECG and blood oxygen, and comprehensive workout tracking.',
                'short_description' => 'Advanced smartwatch with double tap gesture and health sensors.',
                'stock' => 65,
                'image' => 'products/apple-watch-series-9.webp',
                'sold_count' => 2100,
                'view_count' => 53400,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.051,
                'meta' => ['chip' => 'S9', 'display' => 'Always-On Retina', 'feature' => 'Double Tap Gesture, ECG, Blood Oxygen'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 5,
                'name' => 'Samsung Galaxy Watch 6 Classic',
                'price' => 399.00,
                'discount' => 15,
                'sku' => 'SAM-GW6C-47',
                'description' => 'Samsung Galaxy Watch 6 Classic with rotating bezel, Super AMOLED display, advanced sleep coaching, BioActive Sensor, and Google Wear OS for a premium smartwatch experience.',
                'short_description' => 'Classic smartwatch with rotating bezel and sleep coaching.',
                'stock' => 45,
                'image' => 'products/samsung-galaxy-watch-6.webp',
                'sold_count' => 980,
                'view_count' => 31200,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.052,
                'meta' => ['os' => 'Wear OS', 'display' => 'Super AMOLED', 'feature' => 'Rotating Bezel, Advanced Sleep Coaching, BioActive Sensor'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 5,
                'name' => 'Apple Watch Ultra 2',
                'price' => 799.00,
                'discount' => 5,
                'sku' => 'APL-AWU2-49',
                'description' => 'Apple Watch Ultra 2 with precision dual-frequency GPS, 3000-nit display, 36-hour battery, Action button, depth gauge, and titanium case for extreme adventures and diving.',
                'short_description' => 'Rugged titanium adventure watch with precision GPS.',
                'stock' => 25,
                'image' => 'products/apple-watch-ultra-2.webp',
                'sold_count' => 480,
                'view_count' => 21500,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.061,
                'meta' => ['chip' => 'S9', 'display' => '3000-nit Retina', 'battery' => '36 Hours', 'feature' => 'Dual-Frequency GPS, Action Button, Depth Gauge'],
            ],
            [
                'brand_id' => 13,
                'category_id' => 5,
                'name' => 'Xiaomi Watch 2 Pro',
                'price' => 269.00,
                'discount' => 15,
                'sku' => 'XIA-W2PRO-BLK',
                'description' => 'Xiaomi Watch 2 Pro with Google Wear OS, dual-band GPS, AMOLED display, comprehensive health monitoring including body composition analysis, and up to 65 hours battery life.',
                'short_description' => 'Wear OS smartwatch with dual-band GPS and body analysis.',
                'stock' => 55,
                'image' => 'products/xiaomi-watch-2-pro.webp',
                'sold_count' => 670,
                'view_count' => 22300,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.055,
                'meta' => ['os' => 'Wear OS', 'display' => 'AMOLED', 'battery' => '65 Hours', 'feature' => 'Dual-Band GPS, Body Composition Analysis'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 5,
                'name' => 'Samsung Galaxy Watch FE',
                'price' => 199.00,
                'discount' => 12,
                'sku' => 'SAM-GWFE-40',
                'description' => 'Samsung Galaxy Watch FE with BioActive Sensor, sleep tracking, heart rate monitoring, Google Wear OS, and sapphire crystal display offering essential smartwatch features at an affordable price.',
                'short_description' => 'Affordable Samsung smartwatch with essential health features.',
                'stock' => 80,
                'image' => 'products/samsung-galaxy-watch-fe.webp',
                'sold_count' => 1400,
                'view_count' => 37800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.037,
                'meta' => ['os' => 'Wear OS', 'display' => 'Sapphire Crystal', 'feature' => 'BioActive Sensor, Sleep & Heart Rate Monitoring'],
            ],
            [
                'brand_id' => 17,
                'category_id' => 5,
                'name' => 'LG Watch W7',
                'price' => 249.00,
                'discount' => 20,
                'sku' => 'LG-WATCHW7',
                'description' => 'LG Watch W7 with Wear OS, 1.39-inch AMOLED display, 4GB storage, heart rate monitoring, GPS, swim tracking, and IP68 durability for a refined smartwatch experience with mechanical hands.',
                'short_description' => 'Hybrid smartwatch with mechanical hands and Wear OS.',
                'stock' => 15,
                'image' => 'products/lg-watch-w7.webp',
                'sold_count' => 120,
                'view_count' => 6200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.079,
                'meta' => ['os' => 'Wear OS', 'display' => '1.39-inch AMOLED', 'storage' => '4GB', 'feature' => 'Hybrid Design, Mechanical Hands, IP68'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 5,
                'name' => 'Sony SmartWatch 4',
                'price' => 299.00,
                'discount' => 10,
                'sku' => 'SON-SW4-BLK',
                'description' => 'Sony SmartWatch 4 with Google Wear OS, Snapdragon Wear 4100+, 1.4-inch OLED display, GPS, NFC, 5ATM water resistance, and Sony audio integration for a connected lifestyle.',
                'short_description' => 'Sony Wear OS watch with audio integration and NFC.',
                'stock' => 18,
                'image' => 'products/sony-smartwatch-4.webp',
                'sold_count' => 160,
                'view_count' => 7200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.048,
                'meta' => ['os' => 'Wear OS', 'chip' => 'Snapdragon Wear 4100+', 'display' => '1.4-inch OLED', 'feature' => 'GPS, NFC, 5ATM, Sony Audio Integration'],
            ],

            // ==================== 6. CAMERAS (Category ID: 6) ====================
            [
                'brand_id' => 3,
                'category_id' => 6,
                'name' => 'Sony Alpha 7 IV',
                'price' => 2499.00,
                'discount' => 10,
                'sku' => 'SON-A7IV-BODY',
                'description' => 'Sony Alpha 7 IV full-frame mirrorless camera with 33MP Exmor R sensor, 4K 60p video, Real-time Eye AF, 5-axis stabilization, and S-Cinetone color for professional hybrid shooting.',
                'short_description' => 'Professional full-frame hybrid camera with 33MP sensor.',
                'stock' => 25,
                'image' => 'products/sony-alpha-7-iv.webp',
                'sold_count' => 480,
                'view_count' => 25400,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.658,
                'meta' => ['type' => 'Mirrorless Full-Frame', 'sensor' => '33MP Exmor R', 'video' => '4K 60p', 'feature' => 'Real-time Eye AF, 5-axis Stabilization'],
            ],
            [
                'brand_id' => 11,
                'category_id' => 6,
                'name' => 'Canon EOS R6 Mark II',
                'price' => 2499.00,
                'discount' => 8,
                'sku' => 'CAN-R6M2-BODY',
                'description' => 'Canon EOS R6 Mark II full-frame mirrorless with 24.2MP sensor, 40fps electronic shutter, 6K oversampled 4K 60p video, advanced subject detection, and 8-stop IBIS for professionals.',
                'short_description' => 'Fast 40fps full-frame camera with advanced subject tracking.',
                'stock' => 22,
                'image' => 'products/canon-es-os.webp',
                'sold_count' => 390,
                'view_count' => 21800,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.670,
                'meta' => ['type' => 'Mirrorless Full-Frame', 'sensor' => '24.2MP', 'shooting' => '40fps Electronic Shutter', 'video' => '6K Oversampled 4K 60p', 'feature' => '8-stop IBIS'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 6,
                'name' => 'Sony ZV-E1',
                'price' => 2199.00,
                'discount' => 12,
                'sku' => 'SON-ZVE1-BODY',
                'description' => 'Sony ZV-E1 full-frame vlog camera with 12.1MP sensor, 4K 120p, AI-based auto framing, Cinematic Vlog setting, dynamic active mode stabilization, and intelligent 3-capsule microphone.',
                'short_description' => 'Full-frame vlog camera with AI features and stabilization.',
                'stock' => 20,
                'image' => 'products/sony-ZV-E1.webp',
                'sold_count' => 320,
                'view_count' => 21200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.483,
                'meta' => ['type' => 'Vlog Full-Frame', 'sensor' => '12.1MP', 'video' => '4K 120p', 'feature' => 'AI Auto Framing, Cinematic Vlog Setting, Dynamic Active Mode'],
            ],
            [
                'brand_id' => 11,
                'category_id' => 6,
                'name' => 'Canon EOS R50',
                'price' => 679.00,
                'discount' => 10,
                'sku' => 'CAN-R50-KIT',
                'description' => 'Canon EOS R50 mirrorless camera with 24.2MP APS-C sensor, 4K 30p video, advanced subject detection, 15fps shooting, and compact lightweight body perfect for content creators and beginners.',
                'short_description' => 'Compact beginner mirrorless with advanced autofocus.',
                'stock' => 40,
                'image' => 'products/canon-es-os-sss.webp',
                'sold_count' => 560,
                'view_count' => 19800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.375,
                'meta' => ['type' => 'Mirrorless APS-C', 'sensor' => '24.2MP', 'video' => '4K 30p', 'shooting' => '15fps'],
            ],
            [
                'brand_id' => 11,
                'category_id' => 6,
                'name' => 'Canon RF 24-70mm f/2.8L IS USM',
                'price' => 2299.00,
                'discount' => 5,
                'sku' => 'CAN-RF2470-28',
                'description' => 'Canon RF 24-70mm f/2.8L IS USM professional zoom lens with 5-stop optical image stabilization, Nano USM autofocus, and L-series weather-sealed construction for versatile professional shooting.',
                'short_description' => 'Professional L-series standard zoom with stabilization.',
                'stock' => 10,
                'image' => 'products/canon-24-70-1.jpg',
                'sold_count' => 160,
                'view_count' => 8900,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.900,
                'meta' => ['type' => 'Zoom Lens', 'mount' => 'Canon RF', 'aperture' => 'f/2.8', 'feature' => '5-stop Optical IS, Nano USM, Weather-Sealed'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 6,
                'name' => 'Sony FE 70-200mm f/2.8 GM II',
                'price' => 2799.00,
                'discount' => 5,
                'sku' => 'SON-70200GM2',
                'description' => 'Sony FE 70-200mm f/2.8 GM OSS II telephoto zoom with XD linear motors, 4-axis stabilization, G Master optical performance, and lightweight 1.045kg design for sports and wildlife.',
                'short_description' => 'Lightweight G Master telephoto zoom for professionals.',
                'stock' => 8,
                'image' => 'products/Sony-FE-70-200mm-GM-OSS-II-1.jpg',
                'sold_count' => 110,
                'view_count' => 9200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.045,
                'meta' => ['type' => 'Telephoto Zoom Lens', 'mount' => 'Sony E', 'aperture' => 'f/2.8', 'feature' => 'XD Linear Motors, 4-axis Stabilization, Lightweight 1.045kg'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 6,
                'name' => 'Sony Cyber-shot RX100 VII',
                'price' => 1299.00,
                'discount' => 8,
                'sku' => 'SON-RX100M7',
                'description' => 'Sony Cyber-shot RX100 VII premium compact camera with 20.1MP 1-inch sensor, 24-200mm zoom, 20fps blackout-free shooting, 4K HDR video, and real-time tracking in a pocketable body.',
                'short_description' => 'Premium pocket camera with 24-200mm zoom and 20fps.',
                'stock' => 28,
                'image' => 'products/sony-cyber-shot-rx100-VI.webp',
                'sold_count' => 340,
                'view_count' => 15600,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.302,
                'meta' => ['type' => 'Premium Compact', 'sensor' => '20.1MP 1-inch', 'lens' => '24-200mm Zoom', 'feature' => '20fps Blackout-Free Shooting, Real-time Tracking'],
            ],

            // ==================== 7. GAMING (Category ID: 7) ====================
            [
                'brand_id' => 3,
                'category_id' => 7,
                'name' => 'PlayStation 5 Slim',
                'price' => 499.00,
                'discount' => 5,
                'sku' => 'SON-PS5SLIM-1TB',
                'description' => 'Sony PlayStation 5 Slim console with 1TB SSD, 4K gaming up to 120fps, ray tracing, haptic feedback DualSense controller, and Tempest 3D AudioTech in a reduced 30% smaller volume design.',
                'short_description' => 'Next-gen gaming in a slimmer design with 1TB storage.',
                'stock' => 55,
                'image' => 'products/sony-playstation-5-slim.webp',
                'sold_count' => 2800,
                'view_count' => 75000,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 3.20,
                'meta' => ['storage' => '1TB SSD', 'gaming' => '4K up to 120fps', 'feature' => 'Ray Tracing, DualSense Controller, Tempest 3D AudioTech'],
            ],
            [
                'brand_id' => 6,
                'category_id' => 7,
                'name' => 'Xbox Series X',
                'price' => 499.00,
                'discount' => 8,
                'sku' => 'MIC-XBSX-1TB',
                'description' => 'Microsoft Xbox Series X console with 12 TFLOPS, 1TB SSD, 4K gaming at up to 120fps, Dolby Vision, Dolby Atmos, backward compatibility, and Xbox Game Pass ready for the ultimate gaming ecosystem.',
                'short_description' => 'Most powerful Xbox with 12 TFLOPS and Game Pass ready.',
                'stock' => 50,
                'image' => 'products/sony-playstation-x.webp',
                'sold_count' => 2100,
                'view_count' => 64000,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 4.44,
                'meta' => ['gpu' => '12 TFLOPS', 'storage' => '1TB SSD', 'gaming' => '4K up to 120fps', 'feature' => 'Dolby Vision, Dolby Atmos, Backward Compatibility'],
            ],
            [
                'brand_id' => 10,
                'category_id' => 7,
                'name' => 'ASUS ROG Ally',
                'price' => 699.00,
                'discount' => 10,
                'sku' => 'ASU-ROGALLY-Z1E',
                'description' => 'ASUS ROG Ally handheld gaming PC with AMD Ryzen Z1 Extreme, 7-inch 1080p 120Hz display, 512GB SSD, Windows 11, and ROG Armoury Crate SE for AAA gaming anywhere.',
                'short_description' => 'Handheld Windows gaming PC with 120Hz display.',
                'stock' => 35,
                'image' => 'products/asus-rog-ally.jpg',
                'sold_count' => 540,
                'view_count' => 29300,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.608,
                'meta' => ['cpu' => 'AMD Ryzen Z1 Extreme', 'storage' => '512GB SSD', 'display' => '7-inch 1080p 120Hz', 'os' => 'Windows 11'],
            ],
            [
                'brand_id' => 19,
                'category_id' => 7,
                'name' => 'Razer Blade 15',
                'price' => 2499.00,
                'discount' => 8,
                'sku' => 'RAZ-BL15-4070',
                'description' => 'Razer Blade 15 gaming laptop with Intel Core i7-13800H, 16GB RAM, RTX 4070, 1TB SSD, 15.6-inch QHD 240Hz display, and per-key RGB Chroma keyboard in a premium CNC aluminum chassis.',
                'short_description' => 'Premium gaming laptop with 240Hz QHD and Chroma RGB.',
                'stock' => 12,
                'image' => 'products/razer-bl-15.webp',
                'sold_count' => 190,
                'view_count' => 16500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 2.01,
                'meta' => ['cpu' => 'Intel Core i7-13800H', 'gpu' => 'NVIDIA RTX 4070', 'ram' => '16GB', 'storage' => '1TB SSD', 'display' => '15.6-inch QHD 240Hz', 'feature' => 'Per-Key RGB Chroma'],
            ],
            [
                'brand_id' => 19,
                'category_id' => 7,
                'name' => 'Razer Basilisk V3 Pro',
                'price' => 159.00,
                'discount' => 15,
                'sku' => 'RAZ-BV3PRO-WL',
                'description' => 'Razer Basilisk V3 Pro wireless gaming mouse with Razer HyperScroll tilt wheel, Focus Pro 30K optical sensor, 13-zone Chroma lighting, and 90-hour battery life for elite gaming control.',
                'short_description' => 'Wireless gaming mouse with 13-zone RGB and 30K DPI.',
                'stock' => 60,
                'image' => 'products/razer-basilisk-v3.webp',
                'sold_count' => 480,
                'view_count' => 19600,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.112,
                'meta' => ['type' => 'Wireless', 'sensor' => 'Focus Pro 30K Optical', 'battery' => '90 Hours', 'feature' => 'HyperScroll Tilt Wheel, 13-zone Chroma'],
            ],
            [
                'brand_id' => 19,
                'category_id' => 7,
                'name' => 'Razer BlackShark V2 Pro',
                'price' => 199.00,
                'discount' => 20,
                'sku' => 'RAZ-BSV2PRO',
                'description' => 'Razer BlackShark V2 Pro wireless esports headset with Razer HyperClear super wideband mic, Triforce Titanium 50mm drivers, 70-hour battery, and ultra-light 320g design for competitive play.',
                'short_description' => 'Wireless esports headset with 70-hour battery and pro mic.',
                'stock' => 40,
                'image' => 'products/razer-black-shark-v2.webp',
                'sold_count' => 620,
                'view_count' => 21800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.320,
                'meta' => ['type' => 'Wireless', 'drivers' => 'Triforce Titanium 50mm', 'battery' => '70 Hours', 'weight_g' => 320, 'mic' => 'HyperClear Super Wideband'],
            ],
            [
                'brand_id' => 10,
                'category_id' => 7,
                'name' => 'ASUS ROG Swift OLED PG27AQDM',
                'price' => 999.00,
                'discount' => 10,
                'sku' => 'ASU-PG27AQDM',
                'description' => 'ASUS ROG Swift OLED PG27AQDM 27-inch gaming monitor with 1440p, 240Hz, 0.03ms response time, G-Sync compatible, anti-glare micro-texture coating, and 99% DCI-P3 for competitive gaming.',
                'short_description' => '27" OLED gaming monitor with 240Hz and 0.03ms response.',
                'stock' => 18,
                'image' => 'products/asus-rog-swift-oled.webp',
                'sold_count' => 230,
                'view_count' => 15200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 8.30,
                'meta' => ['size' => '27-inch', 'panel' => 'OLED', 'resolution' => '1440p', 'refresh_rate' => '240Hz', 'response' => '0.03ms', 'feature' => 'G-Sync Compatible'],
            ],
            [
                'brand_id' => 12,
                'category_id' => 7,
                'name' => 'Logitech G PRO X Superlight 2',
                'price' => 159.00,
                'discount' => 10,
                'sku' => 'LOG-GPXSL2-BLK',
                'description' => 'Logitech G PRO X Superlight 2 wireless gaming mouse at only 60g with HERO 2 sensor, LIGHTFORCE hybrid switches, 95-hour battery, and pro-grade LIGHTSPEED wireless for tournament play.',
                'short_description' => 'Ultra-light 60g wireless mouse for esports professionals.',
                'stock' => 50,
                'image' => 'products/logitech-gp-pro.webp',
                'sold_count' => 390,
                'view_count' => 17800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.060,
                'meta' => ['type' => 'Wireless', 'weight_g' => 60, 'sensor' => 'HERO 2', 'battery' => '95 Hours', 'feature' => 'LIGHTFORCE Hybrid Switches'],
            ],

            // ==================== 8. ACCESSORIES (Category ID: 8) ====================
            [
                'brand_id' => 1,
                'category_id' => 8,
                'name' => 'Apple MagSafe Charger',
                'price' => 39.00,
                'discount' => 10,
                'sku' => 'APL-MAGSAFE-WHT',
                'description' => 'Apple MagSafe Charger with 15W fast wireless charging for iPhone 15 and 14 series, perfectly aligned magnets for effortless attachment, and compatible with Qi2 charging standards.',
                'short_description' => '15W magnetic wireless charger for iPhone.',
                'stock' => 150,
                'image' => 'products/apple-magsafe-charger.webp',
                'sold_count' => 4500,
                'view_count' => 83000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.045,
                'meta' => ['type' => 'Wireless Charger', 'power' => '15W', 'compatibility' => 'iPhone 15/14 Series, Qi2'],
            ],
            [
                'brand_id' => 12,
                'category_id' => 8,
                'name' => 'Logitech C920s Pro Webcam',
                'price' => 79.00,
                'discount' => 15,
                'sku' => 'LOG-C920SPRO',
                'description' => 'Logitech C920s Pro HD webcam with 1080p 30fps video, dual stereo microphones, privacy shutter, auto light correction, and universal clip for professional video calls and streaming.',
                'short_description' => '1080p HD webcam with privacy shutter for professionals.',
                'stock' => 100,
                'image' => 'products/logitech-c920spro.webp',
                'sold_count' => 3200,
                'view_count' => 67000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.162,
                'meta' => ['type' => 'Webcam', 'resolution' => '1080p 30fps', 'feature' => 'Privacy Shutter, Dual Stereo Mics, Auto Light Correction'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 8,
                'name' => 'Apple AirTag 4-Pack',
                'price' => 99.00,
                'discount' => 8,
                'sku' => 'APL-ATAG-4PK',
                'description' => 'Apple AirTag 4-pack with precision finding, built-in speaker, IP67 water resistance, user-replaceable battery, and seamless Find My network integration for tracking your valuable items.',
                'short_description' => '4-pack item trackers with precision finding.',
                'stock' => 200,
                'image' => 'products/apple-airtag-4pk.webp',
                'sold_count' => 6800,
                'view_count' => 120000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.044,
                'meta' => ['type' => 'Item Tracker', 'feature' => 'Precision Finding, Find My Network, IP67, User-Replaceable Battery'],
            ],
            [
                'brand_id' => 12,
                'category_id' => 8,
                'name' => 'Logitech MX Master 3S',
                'price' => 99.00,
                'discount' => 15,
                'sku' => 'LOG-MX3S-GRPH',
                'description' => 'Logitech MX Master 3S wireless mouse with 8000 DPI, quiet clicks, MagSpeed electromagnetic scroll wheel, USB-C fast charging, and multi-device Flow control for advanced productivity.',
                'short_description' => 'Premium wireless mouse with quiet clicks and 8K DPI.',
                'stock' => 90,
                'image' => 'products/logitech-mmx-3.webp',
                'sold_count' => 2100,
                'view_count' => 46000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.141,
                'meta' => ['type' => 'Wireless Mouse', 'dpi' => '8000', 'feature' => 'Quiet Clicks, MagSpeed Scroll Wheel, Multi-Device Flow'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 8,
                'name' => 'Apple USB-C to Lightning Cable',
                'price' => 19.00,
                'discount' => 5,
                'sku' => 'APL-USBCL-1M',
                'description' => 'Apple USB-C to Lightning cable 1-meter with fast charging support, MFi certified, durable design, and compatibility with iPhone, iPad, and AirPods for reliable everyday charging.',
                'short_description' => 'MFi certified fast charging cable for Apple devices.',
                'stock' => 300,
                'image' => 'products/apple-usb-c-to-lightning-cable.webp',
                'sold_count' => 9800,
                'view_count' => 185000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.020,
                'meta' => ['type' => 'Charging Cable', 'length' => '1m', 'feature' => 'USB-C to Lightning, MFi Certified, Fast Charging'],
            ],
            [
                'brand_id' => 19,
                'category_id' => 8,
                'name' => 'Razer Mouse Dock Pro',
                'price' => 69.00,
                'discount' => 12,
                'sku' => 'RAZ-MDPRO-BLK',
                'description' => 'Razer Mouse Dock Pro with integrated 4000Hz wireless transceiver, magnetic charging, Chroma RGB lighting, and anti-slip base for compatible Razer wireless gaming mice.',
                'short_description' => 'Wireless charging dock with 4K Hz polling rate.',
                'stock' => 45,
                'image' => 'products/razer-mouse-dock.webp',
                'sold_count' => 280,
                'view_count' => 11200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.132,
                'meta' => ['type' => 'Charging Dock', 'feature' => 'Integrated 4000Hz Transceiver, Magnetic Charging, Chroma RGB'],
            ],

            // ==================== 9. MONITORS (Category ID: 9) ====================
            [
                'brand_id' => 2,
                'category_id' => 9,
                'name' => 'Samsung Odyssey Neo G8',
                'price' => 1299.00,
                'discount' => 15,
                'sku' => 'SAM-ONG8-32',
                'description' => 'Samsung Odyssey Neo G8 32-inch curved gaming monitor with 4K UHD, 240Hz refresh rate, 1ms response time, Quantum Matrix HDR2000, and AMD FreeSync Premium Pro for immersive gaming.',
                'short_description' => '32" curved 4K 240Hz gaming monitor with HDR2000.',
                'stock' => 20,
                'image' => 'products/samsung-odyssey-neo-g8.webp',
                'sold_count' => 340,
                'view_count' => 18700,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 7.50,
                'meta' => ['size' => '32-inch', 'panel' => 'VA Curved', 'resolution' => '4K UHD', 'refresh_rate' => '240Hz', 'hdr' => 'Quantum Matrix HDR2000', 'feature' => 'AMD FreeSync Premium Pro'],
            ],
            [
                'brand_id' => 7,
                'category_id' => 9,
                'name' => 'Dell UltraSharp U2723QE',
                'price' => 619.00,
                'discount' => 12,
                'sku' => 'DEL-U2723QE',
                'description' => 'Dell UltraSharp U2723QE 27-inch 4K USB-C Hub monitor with IPS Black technology, 400 nits brightness, 98% DCI-P3, built-in KVM switch, and extensive connectivity for professionals.',
                'short_description' => '27" 4K USB-C hub monitor with IPS Black technology.',
                'stock' => 35,
                'image' => 'products/dell-ultra-sharp-u2723qe.webp',
                'sold_count' => 520,
                'view_count' => 21400,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 6.60,
                'meta' => ['size' => '27-inch', 'panel' => 'IPS Black', 'resolution' => '4K', 'feature' => 'USB-C Hub, 98% DCI-P3, Built-in KVM'],
            ],
            [
                'brand_id' => 17,
                'category_id' => 9,
                'name' => 'LG UltraFine 5K',
                'price' => 1299.00,
                'discount' => 10,
                'sku' => 'LG-UF5K-27',
                'description' => 'LG UltraFine 5K 27-inch display with 5120x2880 resolution, DCI-P3 99%, Thunderbolt 3, built-in camera and speakers, and macOS integration for creative professionals and Apple users.',
                'short_description' => '27" 5K display with Thunderbolt for Apple professionals.',
                'stock' => 15,
                'image' => 'products/lg-ultra-sharp-u2723qe.webp',
                'sold_count' => 230,
                'view_count' => 12800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 8.30,
                'meta' => ['size' => '27-inch', 'panel' => 'IPS 5K', 'resolution' => '5120x2880', 'feature' => 'Thunderbolt 3, DCI-P3 99%, Built-in Camera & Speakers'],
            ],
            [
                'brand_id' => 10,
                'category_id' => 9,
                'name' => 'ASUS ProArt PA279CRV',
                'price' => 499.00,
                'discount' => 10,
                'sku' => 'ASU-PA279CRV',
                'description' => 'ASUS ProArt PA279CRV 27-inch 4K professional monitor with Delta E < 2 color accuracy, 99% DCI-P3, USB-C 96W power delivery, and Calman Verified for creators and photographers.',
                'short_description' => '27" 4K professional monitor with USB-C 96W PD.',
                'stock' => 25,
                'image' => 'products/asus-pro-art-pa279crv.webp',
                'sold_count' => 310,
                'view_count' => 14200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 5.80,
                'meta' => ['size' => '27-inch', 'panel' => 'IPS', 'resolution' => '4K', 'feature' => 'Delta E < 2, 99% DCI-P3, USB-C 96W PD, Calman Verified'],
            ],
            [
                'brand_id' => 20,
                'category_id' => 9,
                'name' => 'Acer Predator X32FP',
                'price' => 899.00,
                'discount' => 12,
                'sku' => 'ACE-PX32FP',
                'description' => 'Acer Predator X32FP 32-inch 4K UHD gaming monitor with 160Hz, 1ms, Mini-LED with 576 zones, DisplayHDR 1000, 99% Adobe RGB, and HDMI 2.1 for console and PC gaming.',
                'short_description' => '32" 4K Mini-LED gaming monitor with 160Hz and HDR1000.',
                'stock' => 16,
                'image' => 'products/acer-predator-x32fp.webp',
                'sold_count' => 190,
                'view_count' => 11800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 9.20,
                'meta' => ['size' => '32-inch', 'panel' => 'Mini-LED', 'resolution' => '4K UHD', 'refresh_rate' => '160Hz', 'hdr' => 'DisplayHDR 1000', 'feature' => '576 Zones, HDMI 2.1'],
            ],

            // ==================== 10. KEYBOARDS (Category ID: 10) ====================
            [
                'brand_id' => 12,
                'category_id' => 10,
                'name' => 'Logitech MX Keys S',
                'price' => 109.00,
                'discount' => 15,
                'sku' => 'LOG-MXKEYSS-GRPH',
                'description' => 'Logitech MX Keys S wireless keyboard with smart illumination, Logi Bolt USB receiver, Bluetooth, USB-C charging, perfect stroke keys, and multi-device connectivity for premium productivity.',
                'short_description' => 'Premium wireless keyboard with smart backlighting.',
                'stock' => 75,
                'image' => 'products/logitech-mx-keyss.webp',
                'sold_count' => 1200,
                'view_count' => 34500,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.810,
                'meta' => ['type' => 'Wireless', 'layout' => 'QWERTY', 'feature' => 'Smart Illumination, Logi Bolt, Multi-Device, USB-C Charging'],
            ],
            [
                'brand_id' => 19,
                'category_id' => 10,
                'name' => 'Razer BlackWidow V4 Pro',
                'price' => 229.00,
                'discount' => 10,
                'sku' => 'RAZ-BWV4PRO',
                'description' => 'Razer BlackWidow V4 Pro mechanical gaming keyboard with Razer Green switches, Chroma RGB, command dial, programmable macro keys, plush magnetic wrist rest, and 8000Hz polling rate.',
                'short_description' => 'Mechanical gaming keyboard with command dial and 8K Hz.',
                'stock' => 35,
                'image' => 'products/razer-blackwow.webp',
                'sold_count' => 310,
                'view_count' => 14700,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.120,
                'meta' => ['type' => 'Mechanical Gaming', 'switch' => 'Razer Green', 'feature' => 'Chroma RGB, Command Dial, 8000Hz Polling Rate'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 10,
                'name' => 'Apple Magic Keyboard',
                'price' => 99.00,
                'discount' => 5,
                'sku' => 'APL-MAGKEY-WHT',
                'description' => 'Apple Magic Keyboard with numeric keypad, scissor mechanism keys, wireless Bluetooth, rechargeable battery, and sleek aluminum design for Mac desktops and iPad productivity.',
                'short_description' => 'Sleek wireless keyboard with numeric keypad for Mac.',
                'stock' => 80,
                'image' => 'products/apple-magic-keyboard.webp',
                'sold_count' => 1800,
                'view_count' => 52000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.390,
                'meta' => ['type' => 'Wireless', 'layout' => 'QWERTY', 'feature' => 'Numeric Keypad, Scissor Mechanism, Rechargeable Battery'],
            ],
            [
                'brand_id' => 12,
                'category_id' => 10,
                'name' => 'Logitech G915 TKL',
                'price' => 199.00,
                'discount' => 20,
                'sku' => 'LOG-G915TKL-BLK',
                'description' => 'Logitech G915 TKL Lightspeed wireless gaming keyboard with low-profile GL mechanical switches, LIGHTSYNC RGB, aircraft-grade aluminum alloy, and 40-hour battery for competitive play.',
                'short_description' => 'Wireless low-profile mechanical keyboard with RGB.',
                'stock' => 40,
                'image' => 'products/logitech-g915.webp',
                'sold_count' => 480,
                'view_count' => 19300,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.810,
                'meta' => ['type' => 'Wireless Mechanical Gaming', 'switch' => 'GL Tactile', 'battery' => '40 Hours', 'feature' => 'Low-Profile, LIGHTSYNC RGB, Aircraft-Grade Aluminum'],
            ],

            // ==================== 11. MICE (Category ID: 11) ====================
            [
                'brand_id' => 12,
                'category_id' => 11,
                'name' => 'Logitech MX Vertical',
                'price' => 99.00,
                'discount' => 20,
                'sku' => 'LOG-MXVERT-GRPH',
                'description' => 'Logitech MX Vertical wireless ergonomic mouse with 57° vertical angle, 4000 DPI sensor, USB-C fast charging, multi-device connectivity, and textured rubber surface for wrist comfort.',
                'short_description' => 'Ergonomic vertical mouse for wrist comfort.',
                'stock' => 60,
                'image' => 'products/logitech-mx-vertical.webp',
                'sold_count' => 820,
                'view_count' => 25600,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.135,
                'meta' => ['type' => 'Wireless Ergonomic', 'dpi' => '4000', 'feature' => '57° Vertical Angle, USB-C Fast Charging, Multi-Device'],
            ],
            [
                'brand_id' => 1,
                'category_id' => 11,
                'name' => 'Apple Magic Mouse',
                'price' => 79.00,
                'discount' => 8,
                'sku' => 'APL-MAGMSE-WHT',
                'description' => 'Apple Magic Mouse with Multi-Touch surface, wireless Bluetooth, rechargeable battery, optimized foot design, and seamless integration with Mac and iPad for smooth gesture-based navigation.',
                'short_description' => 'Multi-Touch wireless mouse optimized for Mac and iPad.',
                'stock' => 70,
                'image' => 'products/apple-magic-mouse2.webp',
                'sold_count' => 1400,
                'view_count' => 43000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.099,
                'meta' => ['type' => 'Wireless', 'feature' => 'Multi-Touch Surface, Bluetooth, Rechargeable'],
            ],
            [
                'brand_id' => 19,
                'category_id' => 11,
                'name' => 'Razer DeathAdder V3',
                'price' => 69.00,
                'discount' => 15,
                'sku' => 'RAZ-DAV3-BLK',
                'description' => 'Razer DeathAdder V3 wired gaming mouse at only 59g with Focus Pro 30K optical sensor, optical Gen-3 switches, 8K Hz polling rate, and speedflex cable for FPS competitive advantage.',
                'short_description' => 'Ultra-light 59g wired gaming mouse for FPS.',
                'stock' => 85,
                'image' => 'products/razer-death-adder.webp',
                'sold_count' => 620,
                'view_count' => 23400,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.059,
                'meta' => ['type' => 'Wired Gaming', 'weight_g' => 59, 'sensor' => 'Focus Pro 30K Optical', 'polling_rate' => '8000Hz'],
            ],

            // ==================== 12. SPEAKERS (Category ID: 12) ====================
            [
                'brand_id' => 14,
                'category_id' => 12,
                'name' => 'JBL Charge 5',
                'price' => 179.00,
                'discount' => 20,
                'sku' => 'JBL-CH5-BLK',
                'description' => 'JBL Charge 5 portable Bluetooth speaker with JBL Pro Sound, optimized long excursion driver, 20-hour battery, IP67 waterproof, built-in powerbank, and PartyBoost for linking multiple speakers.',
                'short_description' => 'Waterproof portable speaker with 20-hour battery and powerbank.',
                'stock' => 110,
                'image' => 'products/jbl-charge-5.webp',
                'sold_count' => 3800,
                'view_count' => 78000,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.960,
                'meta' => ['type' => 'Portable Bluetooth', 'battery' => '20 Hours', 'rating' => 'IP67 Waterproof', 'feature' => 'Built-in Powerbank, PartyBoost'],
            ],
            [
                'brand_id' => 15,
                'category_id' => 12,
                'name' => 'Bose SoundLink Flex',
                'price' => 149.00,
                'discount' => 15,
                'sku' => 'BOS-SLFLEX-BLK',
                'description' => 'Bose SoundLink Flex waterproof Bluetooth speaker with PositionIQ technology, 12-hour battery, rugged design, built-in microphone, and Bose custom transducer for deep clear sound anywhere.',
                'short_description' => 'Rugged waterproof speaker with PositionIQ technology.',
                'stock' => 65,
                'image' => 'products/bose-soundlink-flex.webp',
                'sold_count' => 1100,
                'view_count' => 31200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.540,
                'meta' => ['type' => 'Portable Bluetooth', 'battery' => '12 Hours', 'feature' => 'PositionIQ Technology, Rugged Design, Built-in Mic'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 12,
                'name' => 'Sony SRS-XB100',
                'price' => 59.00,
                'discount' => 18,
                'sku' => 'SON-SRSXB100-BLK',
                'description' => 'Sony SRS-XB100 ultra-portable Bluetooth speaker with Sound Diffusion Processor, 16-hour battery, IP67 rating, strap included, and clear hands-free calling in a compact lightweight body.',
                'short_description' => 'Ultra-portable speaker with 16-hour battery and IP67.',
                'stock' => 150,
                'image' => 'products/sony-srs-XB100.webp',
                'sold_count' => 2900,
                'view_count' => 54000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.274,
                'meta' => ['type' => 'Ultra-Portable Bluetooth', 'battery' => '16 Hours', 'rating' => 'IP67', 'feature' => 'Sound Diffusion Processor, Strap Included'],
            ],
            [
                'brand_id' => 14,
                'category_id' => 12,
                'name' => 'JBL PartyBox 310',
                'price' => 449.00,
                'discount' => 10,
                'sku' => 'JBL-PB310-BLK',
                'description' => 'JBL PartyBox 310 portable party speaker with 240W JBL Pro Sound, dynamic light show, 18-hour battery, guitar and mic inputs, and splashproof design for unforgettable party entertainment.',
                'short_description' => 'Powerful 240W party speaker with dynamic light show.',
                'stock' => 25,
                'image' => 'products/jbl-partybox-310.webp',
                'sold_count' => 380,
                'view_count' => 16300,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 17.40,
                'meta' => ['type' => 'Party Speaker', 'power' => '240W', 'battery' => '18 Hours', 'feature' => 'Dynamic Light Show, Guitar & Mic Inputs, Splashproof'],
            ],

            // ==================== 13. TELEVISIONS (Category ID: 13) ====================
            [
                'brand_id' => 2,
                'category_id' => 13,
                'name' => 'Samsung QN90C Neo QLED 65',
                'price' => 1799.00,
                'discount' => 20,
                'sku' => 'SAM-QN90C-65',
                'description' => 'Samsung QN90C 65-inch Neo QLED 4K TV with Quantum Matrix technology, Neural Quantum Processor 4K, Dolby Atmos, Object Tracking Sound+, and anti-glare screen for stunning home cinema.',
                'short_description' => '65" Neo QLED 4K TV with Quantum Matrix technology.',
                'stock' => 20,
                'image' => 'products/samsung-qn90-c-65.webp',
                'sold_count' => 340,
                'view_count' => 21500,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 24.50,
                'meta' => ['size' => '65-inch', 'panel' => 'Neo QLED', 'resolution' => '4K', 'feature' => 'Quantum Matrix, Neural Quantum Processor 4K, Dolby Atmos'],
            ],
            [
                'brand_id' => 17,
                'category_id' => 13,
                'name' => 'LG C3 OLED 55',
                'price' => 1499.00,
                'discount' => 18,
                'sku' => 'LG-C3OLED-55',
                'description' => 'LG C3 55-inch OLED evo 4K TV with α9 Gen6 AI Processor, Dolby Vision, Dolby Atmos, 120Hz, G-Sync, and webOS 23 for cinematic picture quality and smooth gaming experience.',
                'short_description' => '55" OLED evo 4K TV with AI processor and 120Hz.',
                'stock' => 25,
                'image' => 'products/lg-c3-qled-55.webp',
                'sold_count' => 420,
                'view_count' => 26700,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 17.80,
                'meta' => ['size' => '55-inch', 'panel' => 'OLED evo', 'resolution' => '4K', 'feature' => 'α9 Gen6 AI Processor, Dolby Vision, G-Sync, 120Hz'],
            ],
            [
                'brand_id' => 3,
                'category_id' => 13,
                'name' => 'Sony Bravia XR A80L 65',
                'price' => 1999.00,
                'discount' => 15,
                'sku' => 'SON-XRA80L-65',
                'description' => 'Sony Bravia XR A80L 65-inch OLED 4K TV with Cognitive Processor XR, Google TV, Dolby Vision, acoustic surface audio+, and exclusive PlayStation 5 features for premium entertainment.',
                'short_description' => '65" OLED 4K TV with Cognitive Processor and PS5 features.',
                'stock' => 15,
                'image' => 'products/sony-xr-x80.webp',
                'sold_count' => 210,
                'view_count' => 15400,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 23.30,
                'meta' => ['size' => '65-inch', 'panel' => 'OLED', 'resolution' => '4K', 'feature' => 'Cognitive Processor XR, Acoustic Surface Audio+, Google TV'],
            ],
            [
                'brand_id' => 18,
                'category_id' => 13,
                'name' => 'Philips OLED+908 55',
                'price' => 1599.00,
                'discount' => 12,
                'sku' => 'PHIL-OLED908-55',
                'description' => 'Philips OLED+908 55-inch 4K Ambilight TV with META OLED panel, 7th Gen P5 AI processor, Bowers & Wilkins sound, 144Hz VRR, and Ambilight immersive lighting for cinema experience.',
                'short_description' => '55" Ambilight OLED TV with Bowers & Wilkins sound.',
                'stock' => 12,
                'image' => 'products/philips-oled-908-55.webp',
                'sold_count' => 140,
                'view_count' => 9800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 20.40,
                'meta' => ['size' => '55-inch', 'panel' => 'META OLED', 'resolution' => '4K', 'feature' => 'Ambilight, P5 AI Processor, Bowers & Wilkins Sound, 144Hz VRR'],
            ],

            // ==================== 14. NETWORKING (Category ID: 14) ====================
            [
                'brand_id' => 10,
                'category_id' => 14,
                'name' => 'ASUS RT-AX88U Pro',
                'price' => 299.00,
                'discount' => 15,
                'sku' => 'ASU-RTAX88UPRO',
                'description' => 'ASUS RT-AX88U Pro WiFi 6 router with dual 2.5G ports, 6000Mbps, AiMesh support, AiProtection Pro, VPN Fusion, and extensive parental controls for high-performance home networking.',
                'short_description' => 'WiFi 6 router with dual 2.5G ports and AiProtection.',
                'stock' => 40,
                'image' => 'products/asus-rt-ax88u-pro.webp',
                'sold_count' => 480,
                'view_count' => 17800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 1.02,
                'meta' => ['standard' => 'WiFi 6', 'speed' => '6000Mbps', 'feature' => 'Dual 2.5G Ports, AiMesh, AiProtection Pro, VPN Fusion'],
            ],
            [
                'brand_id' => 8,
                'category_id' => 14,
                'name' => 'HP Aruba Instant On AP22',
                'price' => 159.00,
                'discount' => 10,
                'sku' => 'HP-ARUBAAP22',
                'description' => 'HP Aruba Instant On AP22 WiFi 6 access point with 1774Mbps, OFDMA, MU-MIMO, easy mobile app management, and business-grade security for small business and home office networks.',
                'short_description' => 'WiFi 6 access point for small business and home office.',
                'stock' => 30,
                'image' => 'products/hp-aruba-instant-on-ap22.webp',
                'sold_count' => 220,
                'view_count' => 8200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.380,
                'meta' => ['standard' => 'WiFi 6', 'speed' => '1774Mbps', 'feature' => 'OFDMA, MU-MIMO, Easy App Management, Business-Grade Security'],
            ],
            [
                'brand_id' => 9,
                'category_id' => 14,
                'name' => 'Lenovo Smart Wireless Router',
                'price' => 129.00,
                'discount' => 18,
                'sku' => 'LEN-SWRTR-WF6',
                'description' => 'Lenovo Smart Wireless WiFi 6 router with mesh support, 3000Mbps, easy app setup, parental controls, and four Gigabit LAN ports for comprehensive and reliable whole-home network coverage.',
                'short_description' => 'WiFi 6 mesh router with easy setup and parental controls.',
                'stock' => 50,
                'image' => 'products/lenovo-smart-wireless-router.webp',
                'sold_count' => 360,
                'view_count' => 14200,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.540,
                'meta' => ['standard' => 'WiFi 6', 'speed' => '3000Mbps', 'feature' => 'Mesh Support, Easy App Setup, 4x Gigabit LAN'],
            ],
            [
                'brand_id' => 6,
                'category_id' => 14,
                'name' => 'Microsoft Surface USB-C Travel Hub',
                'price' => 99.00,
                'discount' => 10,
                'sku' => 'MIC-SURFHUB-USBC',
                'description' => 'Microsoft Surface USB-C Travel Hub with Ethernet port, USB-A, USB-C, HDMI, and VGA connectivity in a compact design for Surface devices to enable wired networking and peripheral connection.',
                'short_description' => 'Compact travel hub with Ethernet for Surface devices.',
                'stock' => 60,
                'image' => 'products/microsoft-smart-travel-hub.webp',
                'sold_count' => 520,
                'view_count' => 16800,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.118,
                'meta' => ['ports' => 'Ethernet, USB-A, USB-C, HDMI, VGA', 'feature' => 'Compact Design, For Surface Devices'],
            ],

            // ==================== 15. WEARABLES (Category ID: 15) ====================
            [
                'brand_id' => 2,
                'category_id' => 15,
                'name' => 'Samsung Galaxy Fit 3',
                'price' => 99.00,
                'discount' => 15,
                'sku' => 'SAM-GFIT3-BLK',
                'description' => 'Samsung Galaxy Fit 3 fitness tracker with 1.6-inch AMOLED display, 13-day battery, sleep coaching, heart rate monitoring, 5ATM water resistance, and automatic workout tracking for active lifestyles.',
                'short_description' => 'AMOLED fitness tracker with 13-day battery and 5ATM.',
                'stock' => 120,
                'image' => 'products/samsung-galaxy-fit.webp',
                'sold_count' => 2100,
                'view_count' => 47500,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.021,
                'meta' => ['type' => 'Fitness Tracker', 'display' => '1.6-inch AMOLED', 'battery' => '13 Days', 'rating' => '5ATM', 'feature' => 'Sleep Coaching, Heart Rate Monitoring'],
            ],
            [
                'brand_id' => 16,
                'category_id' => 15,
                'name' => 'Puma Smartwatch',
                'price' => 229.00,
                'discount' => 20,
                'sku' => 'PUMA-SW-BLK',
                'description' => 'Puma Smartwatch with Google Wear OS, Snapdragon Wear 4100, GPS, heart rate, NFC, 5ATM water resistance, and Puma sports-inspired design with unique nylon and aluminum case for athletes.',
                'short_description' => 'Wear OS smartwatch with athletic design and GPS.',
                'stock' => 30,
                'image' => 'products/puma-smartwatch.webp',
                'sold_count' => 220,
                'view_count' => 8700,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.048,
                'meta' => ['type' => 'Smartwatch', 'os' => 'Wear OS', 'chip' => 'Snapdragon Wear 4100', 'feature' => 'GPS, NFC, 5ATM, Sports-Inspired Design'],
            ],
            [
                'brand_id' => 4,
                'category_id' => 15,
                'name' => 'Nike Sport Band for Apple Watch',
                'price' => 49.00,
                'discount' => 10,
                'sku' => 'NIKE-SPBAND-42',
                'description' => 'Nike Sport Band for Apple Watch with compression-molded perforations for breathability, lightweight fluoroelastomer material, and secure pin-and-tuck closure for comfort during intense workouts.',
                'short_description' => 'Breathable sport band for Apple Watch workouts.',
                'stock' => 200,
                'image' => 'products/nikes-sport-band-42.webp',
                'sold_count' => 3400,
                'view_count' => 68000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.028,
                'meta' => ['type' => 'Watch Band', 'material' => 'Fluoroelastomer', 'compatibility' => 'Apple Watch 42/44/45/49mm', 'feature' => 'Compression-Molded Perforations'],
            ],
            [
                'brand_id' => 2,
                'category_id' => 15,
                'name' => 'Samsung Galaxy Ring',
                'price' => 399.00,
                'discount' => 5,
                'sku' => 'SAM-GRING-10',
                'description' => 'Samsung Galaxy Ring smart ring with Samsung Health AI, sleep tracking, heart rate monitoring, skin temperature sensor, 7-day battery, and titanium grade 5 finish for discreet health tracking.',
                'short_description' => 'Smart ring with AI health tracking and 7-day battery.',
                'stock' => 25,
                'image' => 'products/samsung-galaxy-ring.webp',
                'sold_count' => 310,
                'view_count' => 19800,
                'is_featured' => true,
                'is_active' => true,
                'weight' => 0.003,
                'meta' => ['type' => 'Smart Ring', 'material' => 'Titanium Grade 5', 'battery' => '7 Days', 'feature' => 'Samsung Health AI, Sleep Tracking, Heart Rate Monitor, Skin Temperature Sensor'],
            ],
            [
                'brand_id' => 5,
                'category_id' => 15,
                'name' => 'Adidas Running Armband',
                'price' => 19.00,
                'discount' => 25,
                'sku' => 'ADID-RARMBAND-BLK',
                'description' => 'Adidas Running Armband with universal smartphone fit, reflective detailing for nighttime visibility, key pocket, adjustable strap, and sweat-resistant material for comfortable runs and workouts.',
                'short_description' => 'Reflective running armband with key pocket for phones.',
                'stock' => 180,
                'image' => 'products/adidas-running-armband.webp',
                'sold_count' => 4500,
                'view_count' => 72000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.072,
                'meta' => ['type' => 'Armband', 'feature' => 'Universal Fit, Reflective Detailing, Key Pocket, Sweat-Resistant'],
            ],
            [
                'brand_id' => 16,
                'category_id' => 15,
                'name' => 'Puma Fitness Tracker Band',
                'price' => 39.00,
                'discount' => 20,
                'sku' => 'PUMA-FTBAND-RED',
                'description' => 'Puma fitness tracker wristband with step counting, calorie tracking, sleep monitoring, OLED display, 7-day battery, and 3ATM water resistance in a stylish Puma branded silicone design.',
                'short_description' => 'Stylish Puma fitness band with sleep and step tracking.',
                'stock' => 90,
                'image' => 'products/puma-fitness-tracker-band.webp',
                'sold_count' => 1800,
                'view_count' => 41000,
                'is_featured' => false,
                'is_active' => true,
                'weight' => 0.018,
                'meta' => ['type' => 'Fitness Band', 'display' => 'OLED', 'battery' => '7 Days', 'rating' => '3ATM', 'feature' => 'Step & Calorie Tracking, Sleep Monitoring'],
            ],
        ];
        foreach ($products as $product) {
            if (!isset($product['slug'])) {
                $product['slug'] = Str::slug($product['name']);
            }
            if (!isset($product['short_description'])) {
                $product['short_description'] = Str::limit($product['description'], 120);
            }
            if (!isset($product['is_active'])) {
                $product['is_active'] = true;
            }

            Product::create($product);
        }
    }

}
